packages:
  - 'packages/*'
  - 'lsp-engine'
  - 'vscode-extension'
  - 'express-server'
  - 'angular-playground'

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  'liquidjs@https://codeload.github.com/sonuKumar03/liquidjs/tar.gz/5054036ee77f9c097d0c399b7efac99c0c97c194': true
  'liquidjs@https://codeload.github.com/sonuKumar03/liquidjs/tar.gz/9b253aa07d71fe4af5c17f36bdde3b79d5d79825': true
  'liquidjs': true
  lmdb: true
  msgpackr-extract: true
  nice-napi: true

overrides:
  monaco-editor: 'npm:@codingame/monaco-vscode-editor-api@~8.0.4'
